on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
name: Scrape Data
jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install
        working-directory: ./scraper
        run: yarn install
      - name: scrape
        working-directory: ./scraper
        run: yarn start
      - name: publish
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main